- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - rhoam-scorecard-tests
    - happy-path
    image: quay.io/operator-framework/scorecard-test-kuttl:v2.0.0
    labels:
      cluster-product: ocp
      cluster-size: small
      phase: msp-main
      test: happy-path