# permissions for end users to view rhoamtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhoamtenant-viewer-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - rhoamtenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - rhoamtenants/status
  verbs:
  - get
