# permissions for end users to edit rhoamtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhoamtenant-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - rhoamtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - rhoamtenants/status
  verbs:
  - get
