rule_files:
  - rules.yml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: up{rhoam_version=""}
        values: "1+0x10 0+0x10"
    alert_rule_test:
      # rhoam_version is presentfor 10m
      # alert not expected to fire
      - eval_time: 10m
        alertname: CriticalMetricsMissing
        exp_alerts: [ ]
      # rhoam_version is missing for 10m
      # alert expected to fire
      - eval_time: 20m
        alertname: CriticalMetricsMissing
        exp_alerts:
          - exp_labels:
              severity: critical
            exp_annotations:
              message: metrics have been missing for more than 8 minutes

  - interval: 1m
    input_series:
      - series: rhoam_version{version=".*", to_version=""}
        values: "1+0x10 1+0x10"
      - series: up{rhoam_custom_domain=""}
        values: "1+0x10 0+0x10"
    alert_rule_test:
      # rhoam_version & rhoam_custom_domain are present for 10m
      # alert not expected to fire
      - eval_time: 10m
        alertname: CriticalMetricsMissing
        exp_alerts: [ ]
      # rhoam_custom_domain is missing for 10m
      # alert expected to fire
      - eval_time: 20m
        alertname: CriticalMetricsMissing
        exp_alerts:
          - exp_labels:
              severity: critical
            exp_annotations:
              message: metrics have been missing for more than 8 minutes
     