apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests: []
serviceaccount: rhoam-test-runner
storage:
  spec:
    mountPath:
      path: logs/artifacts