global:
  resolve_timeout: 5m
  smtp_smarthost: {{ index .Params "SMTPHost" }}:{{ index .Params "SMTPPort" }}
  smtp_from: {{ index .Params "SMTPFrom" }}
  smtp_auth_username: {{ index .Params "SMTPUsername" }}
  smtp_auth_password: {{ index .Params "SMTPPassword"}}

templates:
  - /etc/alertmanager/config/alertmanager-email-config.tmpl

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
    - match:
        severity: critical
      receiver: critical
    - match:
        alertname: ThreeScaleContainerHighMemory
      receiver: blackhole
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
    - match:
        alertname: RHOAMApiUsageLevel1ThresholdExceeded
      receiver: BUandCustomer
    - match:
        alertname: RHOAMApiUsageLevel2ThresholdExceeded
      receiver: BUandCustomer
    - match:
        alertname: RHOAMApiUsageLevel3ThresholdExceeded
      receiver: BUandCustomer
    - match_re:
        alertname: RHOAMApiUsageSoftLimitReachedTier[0-9]+
      receiver: BU
    - match:
        alertname: RHOAMApiUsageOverLimit
      receiver: BUandCustomer
    - match:
        alertname: RHOAMApiUsageRejectedRequestsMismatch
      receiver: BUandCustomer
receivers:
  - name: blackhole
  - name: default
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToSREAddress" }}
        headers:
          Subject: '{{ index .Params "Subject" }}'
        html: '{{ index .Params "html" }}'
  - name: critical
    pagerduty_configs:
      - service_key: {{ index .Params "PagerDutyServiceKey" }}
        description: '{{ index .Params "Subject" }}'
        details:
          cluster_name: {{ index .Params "clusterName" }}
          cluster_ID: {{ index .Params "clusterID" }}
          console: {{ index .Params "clusterConsole" }}
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToSREAddress" }}
        headers:
          Subject: '{{ index .Params "Subject" }}'
        html: '{{ index .Params "html" }}'
  - name: deadmansswitch
    webhook_configs:
      - url: {{ index .Params "DeadMansSnitchURL" }}
  - name: BU
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToBUAddress" }}'
        headers:
          Subject: '{{ index .Params "Subject" }}'
        html: '{{ index .Params "html" }}'
  - name: BUandCustomer
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToBUAddress" }}, {{ index .Params "SMTPToCustomerAddress" }}'
        headers:
          Subject: '{{ index .Params "Subject" }}'
        html: '{{ index .Params "html" }}'
  - name: SRECustomerBU
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToSREAddress" }}, {{ index .Params "SMTPToBUAddress" }}, {{ index .Params "SMTPToCustomerAddress" }}'
        headers:
          Subject: '{{ index .Params "Subject" }}'
        html: '{{ index .Params "html" }}'
inhibit_rules:
  - source_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'warning'
    target_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'warning'
    equal: ['alertname', 'job', 'label_cronjob_name']
