apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: rhoam-test-container
status:
  containerStatuses:
    - name: sidecar
      ready: true
    # If some tests have failed,
    # the test container's state.terminated.reason would be "Error"
    - name: test
      state:
        terminated:
          reason: Completed